POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YTIxZTA2MTNlY2VmYjI4MDNmNDI0OCIsImlhdCI6MTcyMTkxMDk5NH0.YrKfibeuwkNgmvnhXYhx5aTvAtAgjvDJTxAveooZJMk

{
    "content":"authorized note",
    "important":true
}